version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - "3000:3000"

amber-runner:
  build:
    context: ./amber-runner
    dockerfile: ../docker/runner.Dockerfile
  volumes:
    - ./sim_data:/sim_data
  command: ["python", "runner.py"]

help-service:
  build:
    context: ./help-service
    dockerfile: ../docker/help.Dockerfile
  ports:
    - "5000:5000"
